config/routes.rb
Ttt::Application.routes.draw do
  root :to => "students#index"
  devise_for :users

  match "/sending" =>"application#sending"

  resources :students

  match "/attens/updateRow/:id" => "attens#updateRow"
  match "/attens/editRow/:id" => "attens#editRow"
  resources :attens

  match "/discs/updateRow/:id" => "discs#updateRow"
  match "/discs/editRow/:id" => "discs#editRow"
  resources :discs

  match "/finals/updateRow" => "finals#updateRow"
  match "/finals/editRow" => "finals#editRow"
  resources :finals

  match "labs/editRow/:id" =>"labs#editRow"
  match "labs/updateRow/:id" =>"labs#updateRow"
  resources :labs

  resources :iterations
  match "/iterations/:id/save" => "iterations#save", :via => 'put'
  match "/iterations/single/:id1/:id2" => "iterations#single"
  match "/iterations/editCol/:id" =>"iterations#editCol"
  match "/iterations/updateCol/:id" => "iterations#updateCol"
  match "/iterations/editRow/:id" => "iterations#editRow"
  match "/iterations/updateRow/:id" => "iterations#updateRow"
  resources :projects

end

app/models/student.rb
class Student < ActiveRecord::Base
  attr_accessible :name, :studentID, :email, :address, :phone, :memo,:sum,:grade
  has_one :project, dependent: :destroy
  has_many :iterations , through: :project, dependent: :destroy
  has_one :lab, dependent: :destroy
  has_one :final, dependent: :destroy
  has_one :disc, dependent: :destroy
  has_one :atten, dependent: :destroy
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  # GET /students
  # GET /students.json
  after_filter :sumUpdate
  def sumUpdate
    students = Student.all
    students.each do |student|
    if student.project != nil && student.project.score != nil && student.final != nil && student.final.score != nil && student.lab != nil && student.lab.score != nil && student.disc != nil &&  student.disc.score != nil && student.atten != nil && student.atten.score != nil
      student.update_attributes(sum: student.project.score*0.4+student.final.score*0.4+student.lab.score*0.1+student.disc.score*0.05+student.atten.score*0.05)
      if student.sum >= 90
        student.update_attributes(grade: "A")
      end 
      if student.sum <90 and student.sum >=75
        student.update_attributes(grade: "B")
      end
      if student.sum <75 and student.sum >=60
        student.update_attributes(grade: "C")
      end
      if student.sum <60 
        student.update_attributes(grade: "D")
      end 
    end
   end
  end
  def index
    @students = Student.all
    if @students.length > 1
      @students.sort! {|a,b| b.sum <=> a.sum}
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @students }
    end
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @student = Student.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/new
  # GET /students/new.json
  def new
    @student = Student.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @student }
    end
  end

  # GET /students/1/edit
  def edit
    @student = Student.find(params[:id])
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(params[:student])

    respond_to do |format|
      if @student.save
        @project = Project.create(score: nil, student_id: @student.id)
        @iteration = Iteration.create(iteNum: 1, score: nil, project_id: @project.id, student_id: @student.id )
        @lab = Lab.create(student_id: @student.id)
        @final  = Final.create(student_id: @student.id)
        @disc = Disc.create(student_id: @student.id)
        @atten = Atten.create(student_id: @student.id)
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render json: @student, status: :created, location: @student }
      else
        format.html { render action: "new" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /students/10
  # PUT /students/1.json
  def update
    @student = Student.find(params[:id])

    respond_to do |format|
      if @student.update_attributes(params[:student])
        format.html { redirect_to students_path, notice: 'close' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student = Student.find(params[:id])
    @student.project.destroy
    @updates = ScoreUpdates.where(:studentid => @student.id)
    @updates.each do |u|
      u.destroy
    end
    @student.destroy

    respond_to do |format|
      format.html { redirect_to students_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Student ID" %><br />
    <%= f.text_field :studentID %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing student</h1>

<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Student ID" %><br />
    <%= f.text_field :studentID %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :memo %><br />
    <%= f.text_area :memo, :size => "15x3" %>
  </div>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
    <%= link_to 'Close', ""%>
  </div>
<% end %>

app/views/students/index.html.erb
<html><head>
<% if notice == 'close'%>
	<script type="text/javascript">window.close()</script>
<% end %>
</head><body>

<table class="datalist">
  <caption>Student Grade Sheet</caption>
  <tr>
    <th>Studentid</th>
    <th>Name</th>
    <th><%= link_to 'Project', projects_path %>40%</th>
    <th><%= link_to 'Final', finals_path %>40%</th>
    <th><%= link_to 'Lab', labs_path %>10%</th>
    <th><%= link_to 'Class Discussion', discs_path %>5%</th>
    <th><%= link_to 'Attendence', attens_path %>5%</th>
    <th>Sum</th>
    <th></th>
  </tr>

<% @students.each do |student| %>
  <tr>
    <td><%= student.studentID %></td>
    <td><%= link_to student.name,"javascript:void(0)",:onclick => "window.open('/students/#{student.id}/edit','','width=300,height=500')" %></td>
    <td><% if student.project != nil && student.project.score != nil %>
      <%= student.project.score*0.4 %>
    <% end %></td>
    <td><% if student.final != nil && student.final.score != nil %>
      <%= student.final.score*0.4 %>
    <% end %></td>
    <td><% if student.lab != nil && student.lab.score != nil %>
      <%= student.lab.score*0.1 %>
    <% end %></td>
    <td><% if student.disc != nil && student.disc.score != nil %>
      <%= student.disc.score*0.05 %>
    <% end %></td>
    <td><% if student.atten != nil && student.atten.score != nil %>
      <%= student.atten.score*0.05 %>
    <% end %></td>
    <td>
      <% if student.project != nil && student.project.score != nil && student.final != nil && student.final.score != nil && student.lab != nil && student.lab.score != nil && student.disc != nil &&  student.disc.score != nil && student.atten != nil && student.atten.score != nil %>
      <%= student.project.score*0.4+student.final.score*0.4+student.lab.score*0.1+student.disc.score*0.05+student.atten.score*0.05%>
      <% end %>
    </td>
    <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'New Student', new_student_path %></body>
</html>

app/views/students/new.html.erb
<h1>New student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p>
  <b>Studentid:</b>
  <%= @student.studentID %>
</p>

<p>
  <b>Email:</b>
  <%= @student.email %>
</p>
<p>
  <b>Address:</b>
  <%= @student.address %>
</p>
<p>
  <b>Phone:</b>
  <%= @student.phone %>
</p>
<p>
  <b>Memo:</b>
  <%= @student.memo %>
</p>




<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>