config/routes.rb
Ttt::Application.routes.draw do
  root :to => "students#index"
  devise_for :users

  match "/sending" =>"application#sending"

  resources :students

  match "/attens/updateRow/:id" => "attens#updateRow"
  match "/attens/editRow/:id" => "attens#editRow"
  resources :attens

  match "/discs/updateRow/:id" => "discs#updateRow"
  match "/discs/editRow/:id" => "discs#editRow"
  resources :discs

  match "/finals/updateRow" => "finals#updateRow"
  match "/finals/editRow" => "finals#editRow"
  resources :finals

  match "labs/editRow/:id" =>"labs#editRow"
  match "labs/updateRow/:id" =>"labs#updateRow"
  resources :labs

  resources :iterations
  match "/iterations/:id/save" => "iterations#save", :via => 'put'
  match "/iterations/single/:id1/:id2" => "iterations#single"
  match "/iterations/editCol/:id" =>"iterations#editCol"
  match "/iterations/updateCol/:id" => "iterations#updateCol"
  match "/iterations/editRow/:id" => "iterations#editRow"
  match "/iterations/updateRow/:id" => "iterations#updateRow"
  resources :projects

end

app/models/iteration.rb
class Iteration < ActiveRecord::Base
  attr_accessible :iteNum, :score , :student_id, :project_id
  belongs_to :student
  belongs_to :project
end

app/controllers/iterations_controller.rb
class IterationsController < ApplicationController
  # GET /iterations
  # GET /iterations.json
  after_filter  :proUpdate
  def proUpdate
    projects= Project.all
    projects.each do |p|
      @total = 0
      p.iterations do |i|
        if i.score != nil
          @total = @total +i.score
        end
      end
      p.score = @total/p.iterations.length
    end
    return
  end
  def editRow
    @students = Student.all
    c = 0
    @students.each do |s|
      if s.iterations.length >c
        c = s.iterations.length
      end
    end

    @id = params[:id]
    @student = Student.find(Project.find(@id))
    if c > @student.iterations.length
      redirect_to projects_path, notice: "Some fields of this student is not created yet" and return 
    end 
    @iterations = Project.find(@id).iterations
  end
  def updateRow
    @id = params[:id]
    @iterations = Project.find(@id).iterations
    @iterations.each do |i|
      i.update_attributes(params[i.id.to_s])
    end 
    redirect_to projects_path and return 
  end
  def editCol
    @editIte = params[:id]
    @students = Student.all
    @students.each do |s|
      if !Iteration.find(:first, :conditions => ["student_id =? and iteNum = ?", s.id ,@editIte])
        Iteration.create(:score => nil,
                                      :iteNum => @editIte,
                                      :student_id => s.id,
                                      :project_id => s.project.id)
      end 
    end 
    @iterations = Iteration.where("iteNum = ?", @editIte)
  end
  def updateCol
    @iterations =Iteration.all
    @iterations.each do |i|
      if params[i.id.to_s] != nil
        Iteration.find(i.id).update_attributes(params[i.id.to_s])
      end
    end 
    redirect_to projects_path and return 
  end

  def save
    @student = Student.all
    @student.each do |s|
      s.project.iterations.create(iteNum: params[:id],
                                                    score: params[s.id.to_s][:score], 
                                                    project_id: s.project.id,
                                                    student_id: s.id)
      end 
    redirect_to projects_path and return
  end

  def index
    @students = Student.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @iterations }
    end
  end

  # GET /iterations/1
  # GET /iterations/1.json
  def show
    @iteration = Iteration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @iteration }
    end
  end

  # GET /iterations/new
  # GET /iterations/new.json
  def new
    @students = Student.all
    @c = @students[0].iterations.length
    @students.each do |s|
      if @c != s.iterations.length
        redirect_to projects_path,
                    notice: "Someone's iterations score is not created yet"
      end
    end
  end

  # GET /iterations/1/edit
  def edit
    @iteration = Iteration.find(params[:id])
  end

  # POST /iterations
  # POST /iterations.json
  def create
    @iteration = Iteration.new(params[:iteration])

    respond_to do |format|
      if @iteration.save
        format.html { redirect_to projects_path, notice: 'Iteration was successfully created.' }
        format.json { render json: @iteration, status: :created, location: @iteration }
      else
        format.html { render action: "new" }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /iterations/1
  # PUT /iterations/1.json
  def update
    @iteration = Iteration.find(params[:id])

    respond_to do |format|
      if @iteration.update_attributes(params[:iteration])
        format.html { redirect_to projects_path, notice: 'Iteration was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @iteration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /iterations/1
  # DELETE /iterations/1.json
  def destroy
    @iteration = Iteration.find(params[:id])
    @iteration.destroy

    respond_to do |format|
      format.html { redirect_to iterations_url }
      format.json { head :no_content }
    end
  end
  def single
    @iteration = Iteration.create(iteNum: params[:id2],
                                                       score: nil,
                                                       student_id:params[:id1],
                                                       project_id: Student.find(params[:id1]).project.id
                                                       )

  end
end

app/helpers/iterations_helper.rb
module IterationsHelper
end

app/views/iterations/_form.html.erb
<%= form_for @iteration, url: iteration_path(@iteration.id) do |f| %>
  <% if @iteration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@iteration.errors.count, "error") %> prohibited this iteration from being saved:</h2>

      <ul>
      <% @iteration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :score %><br />
    <%= f.text_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/iterations/edit.html.erb
<h1>Editing iteration</h1>
<%= "For student #{Student.find(@iteration.student_id).name}" %>
<%=  "Of iteration #{@iteration.iteNum}" %>
<%= render 'form' %>


<%= link_to 'Back', projects_path %>

app/views/iterations/editCol.html.erb
<%= "You are editing grades for iteration #{@editIte}" %>



<%= form_tag("/iterations/updateCol/#{@editIte}", method: "put")%>
<table>
	<% @iterations.each do |i|%>
		<tr>
			<td><%= Student.find(i.student_id).name%></td>
			<td><%= text_field(i.id, :score, :value => i.score ) %></td>
		</tr>
	<% end %>
</table>
<%= submit_tag 'save' %>

app/views/iterations/editRow.html.erb
<p>You are editing iteration grades for student:</p>
<%= @student.name%>
<%= form_tag("/iterations/updateRow/#{@id}", method: "put") %>
<table>
	<% @iterations.each do |i| %>
		<tr>
			<td><%= "Iteration#{i.iteNum}"%></td>
			<td><%= text_field(i.id, :score, :value => i.score)%></td>
		</tr>
	<% end %>
</table>
<%= submit_tag 'save' %>

app/views/iterations/index.html.erb
<html>

<table class="datalist">
  <caption>Listing iterations</caption>
  <tr>
    <th>Student Name</th>
    <th>Score</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @students.each do |s| %>
  <tr>
    <td><%=  s.name %></td>
    <% s.iterations.each do |i|%>
      <td><%= i.score %></td>
      <td><%= link_to 'Edit', edit_iteration_path(i) %></td>
    <% end %>
  </tr>
<% end %>
</table>

<br />
<%= link_to 'Back', projects_path %>
<%= link_to 'New Iteration', new_iteration_path %>
</html>

app/views/iterations/new.html.erb
<span style = "font-size : 19px"><%= "This will be iteration #{@c+1}"%></span>
<br /><br /><br />
<%= form_tag("/iterations/#{@c+1}/save", method: "put")%>
	<table>
		<tr>
			<th>Student Name</th>
			<th>Score</th>
		</tr>
	<% @students.each do |s|%>
		<tr>
			<td><%= s.name %></td>
			<td><%= text_field( s.id ,:score) %></td>
		</tr>
	<% end %>
	</table>
<%= submit_tag 'save' %>
<%= link_to 'Back', iterations_path %>

app/views/iterations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Score:</b>
  <%= @iteration.score %>
</p>


<%= link_to 'Edit', edit_iteration_path(@iteration) %> |
<%= link_to 'Back', iterations_path %>

app/views/iterations/single.html.erb
<p>Here you will create a iteration grade for student:</p>
<p><%= Student.find(@iteration.student_id).name%></p>
<%= "Because his iteration #{@iteration.iteNum} is missing" %>
<p>His score is</p>

<%= render 'form' %>