config/routes.rb
Ttt::Application.routes.draw do
  root :to => "students#index"
  devise_for :users

  match "/sending" =>"application#sending"

  resources :students

  match "/attens/updateRow/:id" => "attens#updateRow"
  match "/attens/editRow/:id" => "attens#editRow"
  resources :attens

  match "/discs/updateRow/:id" => "discs#updateRow"
  match "/discs/editRow/:id" => "discs#editRow"
  resources :discs

  match "/finals/updateRow" => "finals#updateRow"
  match "/finals/editRow" => "finals#editRow"
  resources :finals

  match "labs/editRow/:id" =>"labs#editRow"
  match "labs/updateRow/:id" =>"labs#updateRow"
  resources :labs

  resources :iterations
  match "/iterations/:id/save" => "iterations#save", :via => 'put'
  match "/iterations/single/:id1/:id2" => "iterations#single"
  match "/iterations/editCol/:id" =>"iterations#editCol"
  match "/iterations/updateCol/:id" => "iterations#updateCol"
  match "/iterations/editRow/:id" => "iterations#editRow"
  match "/iterations/updateRow/:id" => "iterations#updateRow"
  resources :projects

end

app/models/disc.rb
class Disc < ActiveRecord::Base
  attr_accessible :score, :student_id, :week1, :week10, :week11, :week2, :week3, :week4, :week5, :week6, :week7, :week8, :week9
end

app/controllers/discs_controller.rb
class DiscsController < ApplicationController
  # GET /discs
  # GET /discs.json
  after_filter :updateScore
  def updateScore
    discs = Disc.all
    discs.each do |d|
      total = 0
      s = 0
      num = 0 
      for i in 1..11 do 
        if s = d.send("week#{i}")
          total = total +s 
          num = num +1
        end
      end 
      if num !=0 
      d.update_attributes(score: total/num)
    end
    end
  end
  def editRow
    @discs = Disc.all
  end
  def updateRow
    discs = Disc.all
    discs.each do |d|
      d.update_attributes(params[d.id.to_s])
    end 
    redirect_to discs_path
  end
  def index
    @discs = Disc.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @discs }
    end
  end

  # GET /discs/1
  # GET /discs/1.json
  def show
    @disc = Disc.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @disc }
    end
  end

  # GET /discs/new
  # GET /discs/new.json
  def new
    @disc = Disc.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @disc }
    end
  end

  # GET /discs/1/edit
  def edit
    @disc = Disc.find(params[:id])
  end

  # POST /discs
  # POST /discs.json
  def create
    @disc = Disc.new(params[:disc])

    respond_to do |format|
      if @disc.save
        format.html { redirect_to @disc, notice: 'Disc was successfully created.' }
        format.json { render json: @disc, status: :created, location: @disc }
      else
        format.html { render action: "new" }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /discs/1
  # PUT /discs/1.json
  def update
    @disc = Disc.find(params[:id])

    respond_to do |format|
      if @disc.update_attributes(params[:disc])
        format.html { redirect_to discs_path, notice: 'Disc was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @disc.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discs/1
  # DELETE /discs/1.json
  def destroy
    @disc = Disc.find(params[:id])
    @disc.destroy

    respond_to do |format|
      format.html { redirect_to discs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/discs_helper.rb
module DiscsHelper
end

app/views/discs/_form.html.erb
<%= form_for(@disc) do |f| %>
  <% if @disc.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disc.errors.count, "error") %> prohibited this disc from being saved:</h2>

      <ul>
      <% @disc.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="field">
    <%= f.label :week1 %><br />
    <%= f.text_field :week1 %>
  </div>
  <div class="field">
    <%= f.label :week2 %><br />
    <%= f.text_field :week2 %>
  </div>
  <div class="field">
    <%= f.label :week3 %><br />
    <%= f.text_field :week3 %>
  </div>
  <div class="field">
    <%= f.label :week4 %><br />
    <%= f.text_field :week4 %>
  </div>
  <div class="field">
    <%= f.label :week5 %><br />
    <%= f.text_field :week5 %>
  </div>
  <div class="field">
    <%= f.label :week6 %><br />
    <%= f.text_field :week6 %>
  </div>
  <div class="field">
    <%= f.label :week7 %><br />
    <%= f.text_field :week7 %>
  </div>
  <div class="field">
    <%= f.label :week8 %><br />
    <%= f.text_field :week8 %>
  </div>
  <div class="field">
    <%= f.label :week9 %><br />
    <%= f.text_field :week9 %>
  </div>
  <div class="field">
    <%= f.label :week10 %><br />
    <%= f.text_field :week10 %>
  </div>
  <div class="field">
    <%= f.label :week11 %><br />
    <%= f.text_field :week11 %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/discs/edit.html.erb
<h1>You are editing class discussion scores</h1>
<p>For student: <%= Student.find(@disc.id).name %>
<%= render 'form' %>

<%= link_to 'Back', discs_path %>

app/views/discs/editRow.html.erb
<h1>You are editing class discussion scores</h1>
<p>For: <%= params[:id]%></p>
<%= form_tag("/discs/updateRow/#{params[:id]}", method: "put") %>
	<table>
		<tr>
			<td>Name</td>
			<td>Score</td>
		</tr>
		<% @discs.each do |d|%>
			<tr>
				<td><%= Student.find(d.student_id).name%></td>
				<td><%= text_field(d.id, params[:id],:value => d.send(params[:id]))%></td>
			</tr>
		<% end %>
	</table>
<%= submit_tag 'save' %>
<%= link_to 'Back', discs_path %>

app/views/discs/index.html.erb
<html>

<table class="datalist">
    <caption>Listing Class Discussion Scores</caption>
  <tr>
    <th>Student</th>
    <th>Score</th>
    <th><%= link_to 'Week1', "/discs/editRow/week1" %></th>
    <th><%= link_to 'Week2', "/discs/editRow/week2" %></th>
    <th><%= link_to 'Week3', "/discs/editRow/week3" %></th>
    <th><%= link_to 'Week4', "/discs/editRow/week4" %></th>
    <th><%= link_to 'Week5', "/discs/editRow/week5" %></th>
    <th><%= link_to 'Week6', "/discs/editRow/week6" %></th>
    <th><%= link_to 'Week7', "/discs/editRow/week7" %></th>
    <th><%= link_to 'Week8', "/discs/editRow/week8" %></th>
    <th><%= link_to 'Week9', "/discs/editRow/week9" %></th>
    <th><%= link_to 'Week10', "/discs/editRow/week10" %></th>
    <th><%= link_to 'Week11', "/discs/editRow/week11" %></th>

    <th></th>

  </tr>

<% @discs.each do |disc| %>
  <tr>
    <td><%= Student.find(disc.student_id).name %></td>
    <td><%= disc.score %></td>
    <td><%= disc.week1 %></td>
    <td><%= disc.week2 %></td>
    <td><%= disc.week3 %></td>
    <td><%= disc.week4 %></td>
    <td><%= disc.week5 %></td>
    <td><%= disc.week6 %></td>
    <td><%= disc.week7 %></td>
    <td><%= disc.week8 %></td>
    <td><%= disc.week9 %></td>
    <td><%= disc.week10 %></td>
    <td><%= disc.week11 %></td>
    <td><%= link_to 'Edit', edit_disc_path(disc) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Frontpage', students_path %>
</html>

app/views/discs/new.html.erb
<h1>New disc</h1>

<%= render 'form' %>

<%= link_to 'Back', discs_path %>

app/views/discs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @disc.student_id %>
</p>

<p>
  <b>Score:</b>
  <%= @disc.score %>
</p>

<p>
  <b>Week1:</b>
  <%= @disc.week1 %>
</p>

<p>
  <b>Week2:</b>
  <%= @disc.week2 %>
</p>

<p>
  <b>Week3:</b>
  <%= @disc.week3 %>
</p>

<p>
  <b>Week4:</b>
  <%= @disc.week4 %>
</p>

<p>
  <b>Week5:</b>
  <%= @disc.week5 %>
</p>

<p>
  <b>Week6:</b>
  <%= @disc.week6 %>
</p>

<p>
  <b>Week7:</b>
  <%= @disc.week7 %>
</p>

<p>
  <b>Week8:</b>
  <%= @disc.week8 %>
</p>

<p>
  <b>Week9:</b>
  <%= @disc.week9 %>
</p>

<p>
  <b>Week10:</b>
  <%= @disc.week10 %>
</p>

<p>
  <b>Week11:</b>
  <%= @disc.week11 %>
</p>


<%= link_to 'Edit', edit_disc_path(@disc) %> |
<%= link_to 'Back', discs_path %>