config/routes.rb
Ttt::Application.routes.draw do
  root :to => "students#index"
  devise_for :users

  match "/sending" =>"application#sending"

  resources :students

  match "/attens/updateRow/:id" => "attens#updateRow"
  match "/attens/editRow/:id" => "attens#editRow"
  resources :attens

  match "/discs/updateRow/:id" => "discs#updateRow"
  match "/discs/editRow/:id" => "discs#editRow"
  resources :discs

  match "/finals/updateRow" => "finals#updateRow"
  match "/finals/editRow" => "finals#editRow"
  resources :finals

  match "labs/editRow/:id" =>"labs#editRow"
  match "labs/updateRow/:id" =>"labs#updateRow"
  resources :labs

  resources :iterations
  match "/iterations/:id/save" => "iterations#save", :via => 'put'
  match "/iterations/single/:id1/:id2" => "iterations#single"
  match "/iterations/editCol/:id" =>"iterations#editCol"
  match "/iterations/updateCol/:id" => "iterations#updateCol"
  match "/iterations/editRow/:id" => "iterations#editRow"
  match "/iterations/updateRow/:id" => "iterations#updateRow"
  resources :projects

end

app/models/atten.rb
class Atten < ActiveRecord::Base
  attr_accessible :score, :student_id, :week1, :week10, :week11, :week2, :week3, :week4, :week5, :week6, :week7, :week8, :week9
end

app/controllers/attens_controller.rb
class AttensController < ApplicationController
  # GET /attens
  # GET /attens.json
  after_filter :updateScore
  def updateScore
    attens = Atten.all
    attens.each do |a|
      total = 0
      s = 0
      num = 0 
      for i in 1..11 do 
        if s = a.send("week#{i}")
          total = total +s 
          num = num +1
        end
      end  
      if num !=0
      a.update_attributes(score: total/num)
    end
    end
  end
  def editRow
    @attens = Atten.all
  end
  def updateRow
    attens = Atten.all
    attens.each do |a|
      if a.send(params[:id]).to_s != params[a.id.to_s][params[:id]]
      a.update_attributes(params[a.id.to_s])
      if !ScoreUpdates.find(:first, :conditions =>["studentid= ? and fieldname = ? and tablename = 'Atten'",a.student_id,params[:id]])
        ScoreUpdates.create(studentid:a.student_id, fieldname:params[:id],tablename:"Atten")
      end
    end
    end
    redirect_to attens_path
  end
  def index
    @attens = Atten.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @attens }
    end
  end

  # GET /attens/1
  # GET /attens/1.json
  def show
    @atten = Atten.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @atten }
    end
  end

  # GET /attens/new
  # GET /attens/new.json
  def new
    @atten = Atten.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @atten }
    end
  end

  # GET /attens/1/edit
  def edit
    @atten = Atten.find(params[:id])
  end

  # POST /attens
  # POST /attens.json
  def create
    @atten = Atten.new(params[:atten])

    respond_to do |format|
      if @atten.save
      	   for i in 1..11 do 
      	    if @atten.send("week#{i}") != ""
      	  	@new = ScoreUpdates.create(studentid: @atten.student_id,tablename: "Atten" ,fieldname: "week#{i}")
      	    end
      	  end 
        format.html { redirect_to @atten, notice: 'Atten was successfully created.' }
        format.json { render json: @atten, status: :created, location: @atten }
      else
        format.html { render action: "new" }
        format.json { render json: @atten.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /attens/1
  # PUT /attens/1.json
  def update
    @atten = Atten.find(params[:id])
    for i in 1..11 do
      if params[:atten]["week#{i}"] != Atten.find(params[:id]).send("week#{i}").to_s && !ScoreUpdates.find(:first,:conditions =>["studentid = ? and fieldname = ?",@atten.student_id,"week#{i}"])
      	  @new = ScoreUpdates.create(studentid: @atten.student_id,tablename: "Atten",fieldname: "week#{i}")
      	end
    end
    respond_to do |format|
      if @atten.update_attributes(params[:atten])

        format.html { redirect_to attens_path, notice: 'Atten was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @atten.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /attens/1
  # DELETE /attens/1.json
  def destroy
    @atten = Atten.find(params[:id])
    @atten.destroy

    respond_to do |format|
      format.html { redirect_to attens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/attens_helper.rb
module AttensHelper
end

app/views/attens/_form.html.erb
<%= form_for(@atten) do |f| %>
  <% if @atten.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@atten.errors.count, "error") %> prohibited this atten from being saved:</h2>

      <ul>
      <% @atten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :week1 %><br />
    <%= f.text_field :week1 %>
  </div>
  <div class="field">
    <%= f.label :week2 %><br />
    <%= f.text_field :week2 %>
  </div>
  <div class="field">
    <%= f.label :week3 %><br />
    <%= f.text_field :week3 %>
  </div>
  <div class="field">
    <%= f.label :week4 %><br />
    <%= f.text_field :week4 %>
  </div>
  <div class="field">
    <%= f.label :week5 %><br />
    <%= f.text_field :week5 %>
  </div>
  <div class="field">
    <%= f.label :week6 %><br />
    <%= f.text_field :week6 %>
  </div>
  <div class="field">
    <%= f.label :week7 %><br />
    <%= f.text_field :week7 %>
  </div>
  <div class="field">
    <%= f.label :week8 %><br />
    <%= f.text_field :week8 %>
  </div>
  <div class="field">
    <%= f.label :week9 %><br />
    <%= f.text_field :week9 %>
  </div>
  <div class="field">
    <%= f.label :week10 %><br />
    <%= f.text_field :week10 %>
  </div>
  <div class="field">
    <%= f.label :week11 %><br />
    <%= f.text_field :week11 %>
  </div>
  <div class="actions">
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/attens/edit.html.erb
<h1>You are editing attendence scores</h1>
<p>For student: <%= Student.find(@atten.id).name %>
<%= render 'form' %>
<%= link_to 'Back', attens_path %>

app/views/attens/editRow.html.erb
<h1>You are editing attendence scores</h1>
<p>For <%= params[:id]%> </p>
<%= form_tag("/attens/updateRow/#{params[:id]}", method: "put") %>
	<table>
		<tr>
			<td>Name</td>
			<td>Score</td>
		</tr>
		<% @attens.each do |a|%>
			<tr>
				<td><%= Student.find(a.student_id).name%></td>
				<td><%= text_field(a.id, params[:id],:value => a.send(params[:id]))%></td>
			</tr>
		<% end %>
	</table>
<%= submit_tag 'Save' %>

app/views/attens/index.html.erb
<html>

<table class="datalist">
    <caption>Listing Attendence Scores</caption>
  <tr>
    <th>Student</th>
    <th>Score</th>
    <th><%= link_to 'Week1', "/attens/editRow/week1" %></th>
    <th><%= link_to 'Week2', "/attens/editRow/week2" %></th>
    <th><%= link_to 'Week3', "/attens/editRow/week3" %></th>
    <th><%= link_to 'Week4', "/attens/editRow/week4" %></th>
    <th><%= link_to 'Week5', "/attens/editRow/week5" %></th>
    <th><%= link_to 'Week6', "/attens/editRow/week6" %></th>
    <th><%= link_to 'Week7', "/attens/editRow/week7" %></th>
    <th><%= link_to 'Week8', "/attens/editRow/week8" %></th>
    <th><%= link_to 'Week9', "/attens/editRow/week9" %></th>
    <th><%= link_to 'Week10', "/attens/editRow/week10" %></th>
    <th><%= link_to 'Week11', "/attens/editRow/week11" %></th>
    <th></th>

  </tr>

<% @attens.each do |atten| %>
  <tr>
    <td><%= Student.find(atten.student_id).name %></td>
    <td><%= atten.score %></td>
    <td><%= atten.week1 %></td>
    <td><%= atten.week2 %></td>
    <td><%= atten.week3 %></td>
    <td><%= atten.week4 %></td>
    <td><%= atten.week5 %></td>
    <td><%= atten.week6 %></td>
    <td><%= atten.week7 %></td>
    <td><%= atten.week8 %></td>
    <td><%= atten.week9 %></td>
    <td><%= atten.week10 %></td>
    <td><%= atten.week11 %></td>
    <td><%= link_to 'Edit', edit_atten_path(atten) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Frontpage', students_path %>
</html>

app/views/attens/new.html.erb
<h1>New atten</h1>

<%= render 'form' %>

<%= link_to 'Back', attens_path %>

app/views/attens/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Student:</b>
  <%= @atten.student_id %>
</p>

<p>
  <b>Score:</b>
  <%= @atten.score %>
</p>

<p>
  <b>Week1:</b>
  <%= @atten.week1 %>
</p>

<p>
  <b>Week2:</b>
  <%= @atten.week2 %>
</p>

<p>
  <b>Week3:</b>
  <%= @atten.week3 %>
</p>

<p>
  <b>Week4:</b>
  <%= @atten.week4 %>
</p>

<p>
  <b>Week5:</b>
  <%= @atten.week5 %>
</p>

<p>
  <b>Week6:</b>
  <%= @atten.week6 %>
</p>

<p>
  <b>Week7:</b>
  <%= @atten.week7 %>
</p>

<p>
  <b>Week8:</b>
  <%= @atten.week8 %>
</p>

<p>
  <b>Week9:</b>
  <%= @atten.week9 %>
</p>

<p>
  <b>Week10:</b>
  <%= @atten.week10 %>
</p>

<p>
  <b>Week11:</b>
  <%= @atten.week11 %>
</p>


<%= link_to 'Edit', edit_atten_path(@atten) %> |
<%= link_to 'Back', attens_path %>